version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    env_file:
      - .env
    environment:
      - API_URL=http://backend:8000
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge